.TH .ATHENA_UI 1 2025-May "internal" "@title Get Athena UI Path"
.SH NAME
.athena_ui \- .athena_ui()
.SH SYNOPSIS
\fI.athena_ui()\fR
.SH DESCRIPTION
.PP
Internal function to resolve the file path of Athena's web interface.
.PP
.SH VALUE
.PP
(character) Full path to the package's web resources directory.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function..athena_ui at http.R:line 50
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
