.TH BUILD_OLLAMA_TOOLS 1 2025-May "" "build the ollama ai tools set from the R# runtime objects"
.SH NAME
build_ollama_tools \- build_ollama_tools(
    <i>deepseek</i> = <span style='color: blue !important;'>NULL</span>)
.SH SYNOPSIS
\fIbuild_ollama_tools(
    <i>deepseek</i> = <span style='color: blue !important;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBdeepseek\fB \fR\- NULL. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.build_ollama_tools at ollama_tools.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
