.TH DOWNLOAD_FILE_PROXY 1 2025-May "" "download the given file by key query"
.SH NAME
download_file_proxy \- download_file_proxy(key)
.SH SYNOPSIS
\fIdownload_file_proxy(key)\fR
.SH OPTIONS
.PP
\fBkey\fB \fR\- . the hash key of the associated file for make download
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.download_file_proxy at proxy.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
