.TH EXEC_R 1 2025-May "" "exec_r"
.SH NAME
exec_r \- exec_r(webContext, req, response)
.SH SYNOPSIS
\fIexec_r(webContext, req, response)\fR
.SH OPTIONS
.PP
\fBwebContext\fB \fR\- . 
.PP
.PP
\fBreq\fB \fR\- . 
.PP
.PP
\fBresponse\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.exec_r at rscript.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
