.TH FILE_PROXY_KEY 1 2025-Jun "" "file_proxy_key"
.SH NAME
file_proxy_key \- file_proxy_key(file)
.SH SYNOPSIS
\fIfile_proxy_key(file)\fR
.SH OPTIONS
.PP
\fBfile\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.file_proxy_key at utils.R:line 100
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
