.TH HANDLEHTTPGET 1 2025-Jun "" "@title Handle HTTP GET Request"
.SH NAME
handleHttpGet \- handleHttpGet(req, response)
.SH SYNOPSIS
\fIhandleHttpGet(req, response)\fR
.SH DESCRIPTION
.PP
Processes incoming HTTP GET requests, serving static files or executing R context scripts.
.PP
.SH OPTIONS
.PP
\fBreq\fB \fR\- . 
.PP
.PP
\fBresponse\fB \fR\- . 
.PP
.SH VALUE
.PP
Modifies `response` object in-place. No explicit return value.
.PP
.SH DETAILS
.PP
1. Follows similar debug and routing logic as \code{handleHttpPost}.\cr 2. Additional static file handling: Serves files from `wwwroot` via \code{host_file()} if path exists.\cr 3. Only executes R script via \code{exec_r()} when no static file matches.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.handleHttpGet at get.R:line 12
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
