.TH HANDLEHTTPGET 1 2025-May "" "Handle http GET request"
.SH NAME
handleHttpGet \- handleHttpGet(wwwroot, webContext, req, response)
.SH SYNOPSIS
\fIhandleHttpGet(wwwroot, webContext, req, response)\fR
.SH OPTIONS
.PP
\fBwwwroot\fB \fR\- . 
.PP
.PP
\fBwebContext\fB \fR\- . 
.PP
.PP
\fBreq\fB \fR\- . 
.PP
.PP
\fBresponse\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.handleHttpGet at http.R:line 41
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
