.TH IMAGE_URL 1 2025-May "" "creaate image url"
.SH NAME
image_url \- image_url(img.file)
.SH SYNOPSIS
\fIimage_url(img.file)\fR
.SH OPTIONS
.PP
\fBimg.file\fB \fR\- . 
.PP
.SH DETAILS
.PP
convert the local image file path as the url could be used as the src attribute value of the html img tag. images format supports svg/png/bmp/jpg/jpeg/webp/gif.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.image_url at utils.R:line 37
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
