.TH READ_IMAGE 1 2025-May "" "read image file"
.SH NAME
read_image \- read_image(file)
.SH SYNOPSIS
\fIread_image(file)\fR
.SH OPTIONS
.PP
\fBfile\fB \fR\- . the file path of the target image file for display by this function
.PP
.SH DETAILS
.PP
read the image file and returns the base64 encoded data uri string for display on the html web ui
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.read_image at utils.R:line 23
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
