.TH READ_TEXT 1 2025-Jun "" "read text file"
.SH NAME
read_text \- read_text(file)
.SH SYNOPSIS
\fIread_text(file)\fR
.SH OPTIONS
.PP
\fBfile\fB \fR\- . the file path of the target text file for read by this function
.PP
.SH DETAILS
.PP
read the given file as plain text file, this function returns the plain text data of the input file
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.read_text at utils.R:line 11
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
