.TH ROUTER 1 2025-May "" "Route url as local R script file"
.SH NAME
router \- router(url, webContext)
.SH SYNOPSIS
\fIrouter(url, webContext)\fR
.SH OPTIONS
.PP
\fBurl\fB \fR\- . the url object that parsed from the http request.
.PP
.PP
\fBwebContext\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.router at rscript.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
