.TH RUN_HTTP 1 2025-May "" "run_http"
.SH NAME
run_http \- run_http(
    <i>httpPort</i> = <span style='color: #500000;'><strong>'80'</strong></span>,
    <i>webContext</i> = <span style='color: brown;'><strong>'./wwwroot'</strong></span>)
.SH SYNOPSIS
\fIrun_http(
    <i>httpPort</i> = <span style='color: #500000;'><strong>'80'</strong></span>,
    <i>webContext</i> = <span style='color: brown;'><strong>'./wwwroot'</strong></span>)\fR
.SH OPTIONS
.PP
\fBhttpPort\fB \fR\- '80'. 
.PP
.PP
\fBwebContext\fB \fR\- './wwwroot'. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.run_http at http.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
