.TH SET_PROXY 1 2025-Jun "" "create file proxy"
.SH NAME
set_proxy \- set_proxy(file)
.SH SYNOPSIS
\fIset_proxy(file)\fR
.SH OPTIONS
.PP
\fBfile\fB \fR\- . the target file path for make convert to download url
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.set_proxy at utils.R:line 25
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
