.TH SET_PROXY 1 2025-May "" "create file proxy"
.SH NAME
set_proxy \- set_proxy(file)
.SH SYNOPSIS
\fIset_proxy(file)\fR
.SH OPTIONS
.PP
\fBfile\fB \fR\- . the target file path for make convert to download url
.PP
.SH DETAILS
.PP
convert the local file path as url link on the cdn proxy server, this function returns file url on the cdn server. you should generates a html anchor link html element to make this file download available to the user.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.set_proxy at utils.R:line 25
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
