#' Download file by hash key
#'
#' @description
#' Retrieves and downloads a file from proxy storage based on hash key lookup.
#' This function handles both file retrieval and HTTP response generation.
#'
#' @param key A 32-character hash string associated with the target file.
#'    Hash format should follow "XX...XX" pattern (e.g. "a1b2c3...z9").
#'
#' @return
#' * When file exists: Returns file metadata through `file.info()`
#' * When file not found: Returns HTTP 404 response list containing:
#'   - code: HTTP status code
#'   - info: Error message string
#'
#' @examples
#' \dontrun{
#' # Valid request
#' download_file_proxy("a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6")
#'
#' # Invalid request
#' download_file_proxy("invalid_key")
#' }
#'
#' @export
#' @family proxy-storage
#' @seealso \code{\link{proxy_realpath}} for path resolution logic
#'
#' @section HTTP Endpoint:
#' This function maps to API endpoint:
#' - URL: "/get/file"
#' - Method: "GET"
#' 
[@url "/get/file"]
[@http "get"]
const download_file_proxy = function(key) {
    const hashfile = proxy_realpath(key);

    if (nchar(hashfile) == 0) {
        list(code = 404, info = `no file could be found by the hash key ${key}.`);
    } else {
        # push file download
        file.info(hashfile, clr_obj = TRUE);
    }
}

#' Resolve file storage path
#'
#' @description
#' Constructs physical file path using hash key segmentation strategy.
#' Files are stored in nested directories derived from hash segments to avoid
#' filesystem overload in high-concurrency environments.
#'
#' @param key A 32-character hash string generated by proxy storage system.
#'    Must contain at least 25 characters for valid path resolution.
#'
#' @return
#' Character string representing full file path following structure:
#' `<tempdir>/<3-5_char_substr>/<23-25_char_substr>/<key>`
#' Returns empty string if no matching file found.
#'
#' @examples
#' \dontrun{
#' proxy_realpath("a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6")
#' }
#'
#' @export
#' @keywords internal
const proxy_realpath = function(key) {
    const tempdir  = getOption("proxy_tmp");
    const tempfile = file.path(tempdir, substr(key, 3,5), substr(key, 23,25));
    const files = list.files(tempfile, pattern = "*.*");
    
    files 
    |> which(f -> basename(f) == key) 
    |> .Internal::first()
    ;
}